num_classes: 10
epochs: 100
grad_clip: 5.0
log_frequency: 100
adjust_weight_decay: true
model:
  name: PreActRobustNetwork
  channel_configs:
  - 16
  - 256
  - 512
  - 512
  depth_configs:
  - 9
  - 4
  - 4
  drop_rate_config:
  - 0.0
  - 0.0
  - 0.0
  num_classes: 10
  stride_config:
  - 1
  - 2
  - 2
  zero_init_residual: false
  activations:
  - ReLU
  - ReLU
  - ReLU
  normalizations:
  - BatchNorm
  - BatchNorm
  - BatchNorm
  kernel_size_configs:
  - 3
  - 3
  - 3
  block_types:
  - basic_block
  - basic_block
  - basic_block
criterion:
  name: MadrysLoss
  epsilon: 0.03137254901960784
  perturb_steps: 7
  step_size: 0.00784313725490196
dataset:
  name: DatasetGenerator
  train_batch_size: 128
  eval_batch_size: 100
  num_of_workers: 8
  dataset_type: CIFAR10
  data_path: ../../datasets
  valset: true
optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5e-4
  momentum: 0.9
scheduler:
  name: MultiStepLR
  milestones:
  - 75
  - 90
  - 100
  gamma: 0.1
Params: '47.06'
FLOPs: '16104.23'
